mirrorprobe / docs: - document a scenario where the mirrorprobe could fail on machines with little   memories and many mirrors to check.
  This issue started to occur on a machine with 512M of RAM when the number of
  probed mirrors reached 100. ulimit -s was 8192 there. The stack trace was:

     File "/usr/bin/mirrorprobe", line 324, in <module>
       main()
     File "/usr/bin/mirrorprobe", line 259, in main
       t.start()
     File "/usr/lib/python2.6/threading.py", line 471, in start
       _start_new_thread(self.__bootstrap, ())
  thread.error: can't start new thread

  The fix is to document how to use ulimit -s to allow starting enough threads again.

  In addition, to facilitate to spot errors like this, no longer recommend to
  redirect stdout and stderr of the mirrorprobe to /dev/null. (It is no longer
  necessary, as per r7780.)